config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  resources :tweets
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :tweet_tags
  has_many :tags, through: :tweet_tags
  before_validation :link_check, on: :create

  validates :message, presence: true
  validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}, on: :create
  
  after_validation :apply_link, on: :create

  private

  def link_check
    check = false
    check = if message.include? 'http://'
              true
            elsif message.include? 'https://'
              true
            else
              false
            end

    if check == true
      arr = message.split
      index = arr.map { |x| x.include? 'http' }.index(true)
      self.link = arr[index]
      arr[index] = "#{arr[index][0..20]}..." if arr[index].length > 23

      self.message = arr.join(' ')
    end
  end

  def apply_link
  	arr = self.message.split
  	index = arr.map { |x| x.include?("http://") || x.include?("https://") }.index(true)

  	if index
  		url = arr[index]
  		arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
  	end

  	self.message = arr.join(" ")
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
    belongs_to :tweet
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  serialize :following, Array

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
    @following_tweets = []

    if current_user
      Tweet.all.each do |tweet|
        if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
          @following_tweets.push(tweet)
        end
      end
    else @following_tweets = Tweet.all
    end
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    # We are adding the user.id of the user you want to
    # follow to your following array.
    # and we want to make sure it's saved in there as an integer
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end


    def tag_tweets
      @tag = Tag.find(params[:id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)
    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_tagged(tweet)
    message_arr = []
    message_arr = tweet.message.split
    message_arr.each_with_index do |word, index|
      next unless word[0] == '#'
      tag = if Tag.pluck(:phrase).include?(word.downcase)
              Tag.find_by(phrase: word.downcase)
            else
              Tag.create(phrase: word.downcase)
            end
      tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
      message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
    end

    tweet.message = message_arr.join(' ')
    tweet
  end
end

app/views/epicenter/feed.html.erb
<% if current_user %>
<div class="profile">
  <p class="handle">Welcome, @<%= current_user.username %></p>
  <p>Here is what your "friends" are saying:</p>
</div>
<% else %>
<div class="profile">
  <p class="handle">Welcome, stranger!</p>
  <p><%= link_to 'Click here', '/users/sign_in' %> to sign in</p>
  <p>Not already a twatter? <%= link_to 'Sign up here', '/users/sign_up' %></p>
</div>
<% end %>

<br>

<div class"feed-container">
  <% @following_tweets.reverse.each do |tweet| %>
    <div>
      <div class="">
        <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
        •
        <span class="timestamp"><%= time_ago_in_words(tweet.created_at) %> ago</span>
      </div>

      <p><%= tweet.message.html_safe %></p>
      <p><%= link_to 'Show', tweet %></p>
    </div>
    <hr>
  <% end %>
</div>

app/views/epicenter/show_user.html.erb
<div class="profile">
  <b>@<%= @user.username %>'s Profile & Tweets</b>
  <p><%= @user.name %></p>
  <p><%= @user.location %></p>
  <p><%= @user.bio %></p>
</div>

<p>
  <% if current_user.following.include?(@user.id) %>
    <%= link_to "Unfollow", unfollow_path(id: @user.id), class: "btn btn-danger" %>
  <% else %>
    <% if current_user.id != @user.id %>
      <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
    <% end %>
  <% end %>

</p>

<% @user.tweets.reverse.each do |tweet| %>
  <div>
    <p class="handle">@<%= @user.username %></p>
    <p><%= tweet.message.html_safe %></p>
    <p class="timestamp"><%= time_ago_in_words(tweet.created_at) %> ago</p>
    <hr>
  </div>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<div class="hashtag-feed">
  Related to <%= @tag.phrase %>
</div>
<br><br>

<div class="row feed-container">
  <!-- a place for current user stats -->
  <div>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
      <p>
        <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
        •
        <span class="timestamp"><%= time_ago_in_words(tweet.created_at) %> ago</span>
      </p>
      <p>
        <%= tweet.message.html_safe %>
      </p>
      <hr>
    <% end %>
  </div>
</div>

<div><%= link_to "Back to feed", root_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= favicon_link_tag asset_path('favicon-twitter.ico'), :rel => 'icon', :type =>  'image/png' %>
  </head>

  <!-- app/views/layouts/application.html.erb -->
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span style="font-size: 3rem;">
            <a href="/"><i class="fab fa-twitter twitter"></i></a>
          </span>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.avatar.blank? == false %>
                    <%= image_tag current_user.avatar.url, size:25, class: "user-pic-nav" %>
                  <% end %>
                  @<%= current_user.username %>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
                  <li><%= link_to "View Profile", show_user_path(id: current_user.id) %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Cancel', @tweet %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td>@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= tweet.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back to feed', root_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>

<% if @tweet.user.id == current_user.id %>
  <%= link_to 'Back to Feed', root_path %>
  |
  <%= link_to 'Edit', edit_tweet_path(@tweet) %>
  |
  <%= link_to 'Delete', @tweet, method: :delete, data: { confirm: "Are you sure you want to delete this tweet? This cannot be undone." } %>
<% else %>
  <%= link_to 'Back to Feed', root_path %>
<% end %>